# Generated by Django 6.0.3 on 2026-04-18 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0008_finalize_permanent_assignments'),
        ('students', '0005_student_passport_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_score', models.DecimalField(blank=True, decimal_places=2, help_text='The sessional cumulative average used for the decision.', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('PROMOTED', 'Promoted'), ('PROMOTED_TRIAL', 'Promoted on Trial'), ('REPEATED', 'Repeated'), ('GRADUATED', 'Graduated'), ('WITHDRAWN', 'Withdrawn')], default='PROMOTED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_from', to='academics.classarm')),
                ('from_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='academics.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_history', to='students.student')),
                ('to_class', models.ForeignKey(blank=True, help_text='Target class for next session. Null if graduated or withdrawn.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_to', to='academics.classarm')),
                ('to_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='academics.academicsession')),
            ],
            options={
                'verbose_name_plural': 'Promotion Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
