# Generated by Django 6.0.3 on 2026-04-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emergency_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
