# Generated by Django 6.0.3 on 2026-04-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/passports/'),
        ),
    ]
