# Generated by Django 6.0.3 on 2026-04-12 12:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_alter_subjectteacherassignment_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(help_text='Upload scheme material (PDF, DOCX, DOC, PPTX only)', upload_to='schemes/attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'pptx'])])),
                ('description', models.TextField(blank=True, help_text='Briefly describe the scheme or add notes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='academics.classarm')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='academics.academicsession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='academics.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='academics.term')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_schemes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheme of Work',
                'verbose_name_plural': 'Schemes of Work',
                'ordering': ['-session__start_date', 'term', 'class_arm__level__order', 'subject__name'],
                'unique_together': {('subject', 'class_arm', 'term', 'session')},
            },
        ),
    ]
