# Generated by Django 6.0.3 on 2026-04-01 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=10)),
                ('address', models.TextField(blank=True)),
                ('state_of_origin', models.CharField(blank=True, max_length=50)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='staff/profile_pics/')),
                ('employment_date', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('VOLUNTEER', 'Volunteer')], default='FULL_TIME', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('date_left', models.DateField(blank=True, null=True)),
                ('highest_qualification', models.CharField(blank=True, choices=[('SSCE', 'SSCE / WAEC'), ('OND', 'OND'), ('HND', 'HND'), ('BSC', 'B.Sc / B.Ed / BA'), ('PGD', 'PGD'), ('MSC', 'M.Sc / M.Ed / MA'), ('PHD', 'Ph.D'), ('NCE', 'NCE')], max_length=10)),
                ('qualification_subject', models.CharField(blank=True, help_text='e.g. B.Sc Mathematics', max_length=100)),
                ('institution', models.CharField(blank=True, help_text='Institution where highest qualification was obtained', max_length=200)),
                ('year_obtained', models.PositiveIntegerField(blank=True, null=True)),
                ('teaching_certificate', models.CharField(blank=True, help_text='e.g. PGDE, NCE', max_length=100)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=100)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=50)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=15)),
                ('next_of_kin_address', models.TextField(blank=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
