# Generated by Django 6.0.3 on 2026-04-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_subjectteacherassignment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectteacherassignment',
            unique_together={('subject', 'class_arm')},
        ),
        migrations.RemoveField(
            model_name='subjectteacherassignment',
            name='session',
        ),
        migrations.RemoveField(
            model_name='subjectteacherassignment',
            name='term',
        ),
    ]
