# Generated by Django 6.0.3 on 2026-04-17 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_remove_assignment_session_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='classarmsubject',
            name='arm_name',
            field=models.CharField(blank=True, help_text='e.g. A, B, Science', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='classarmsubject',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arm_subjects', to='academics.classlevel'),
        ),
        migrations.AddField(
            model_name='subjectteacherassignment',
            name='arm_name',
            field=models.CharField(blank=True, help_text='e.g. A, B, Science', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subjectteacherassignment',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.classlevel'),
        ),
        migrations.AlterField(
            model_name='subjectteacherassignment',
            name='class_arm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.classarm'),
        ),
    ]
