# Generated by Django 6.0.3 on 2026-04-17 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_add_permanent_assignment_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classarmsubject',
            unique_together={('class_level', 'arm_name', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectteacherassignment',
            unique_together={('subject', 'class_level', 'arm_name')},
        ),
        migrations.AlterField(
            model_name='classarmsubject',
            name='arm_name',
            field=models.CharField(default='TEMP', help_text='e.g. A, B, Science', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classarmsubject',
            name='class_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arm_subjects', to='academics.classlevel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classarmsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arm_offerings', to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='subjectteacherassignment',
            name='arm_name',
            field=models.CharField(default='TEMP', help_text='e.g. A, B, Science', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjectteacherassignment',
            name='class_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.classlevel'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='classarmsubject',
            name='class_arm',
        ),
        migrations.RemoveField(
            model_name='classarmsubject',
            name='is_compulsory',
        ),
        migrations.RemoveField(
            model_name='subjectteacherassignment',
            name='class_arm',
        ),
    ]
