# Generated by Django 6.0.3 on 2026-04-29 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_finalize_permanent_assignments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassSubject',
        ),
    ]
