# Generated by Django 6.0.3 on 2026-04-03 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('CA1', 'First Continuous Assessment'), ('CA2', 'Second Continuous Assessment'), ('EXAM', 'End of Term Examination')], default='EXAM', max_length=10)),
                ('obj_marks', models.PositiveIntegerField(default=30, help_text='Maximum marks for CBT/Objective section')),
                ('theory_marks', models.PositiveIntegerField(default=30, help_text='Maximum marks for Theory section')),
                ('ca1_marks', models.PositiveIntegerField(default=20, help_text='Maximum marks for CA1')),
                ('ca2_marks', models.PositiveIntegerField(default=20, help_text='Maximum marks for CA2')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='CBT exam duration in minutes')),
                ('randomize_questions', models.BooleanField(default=True)),
                ('show_result_immediately', models.BooleanField(default=False)),
                ('submission_deadline', models.DateTimeField(blank=True, help_text='Deadline for teacher to submit/activate this exam', null=True)),
                ('deadline_penalty_logged', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_VETTING', 'Pending Vetting'), ('VETTED', 'Vetted'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('vetted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('vetting_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_approved', to=settings.AUTH_USER_MODEL)),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.classarm')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_created', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.academicsession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.term')),
                ('vetted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_vetted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('subject', 'class_arm', 'session', 'term', 'exam_type')},
            },
        ),
        migrations.CreateModel(
            name='ExamDeadlinePenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='examinations.exam')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_penalties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('AUTO_SUBMITTED', 'Auto Submitted (Time Up)'), ('ABANDONED', 'Abandoned')], default='IN_PROGRESS', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_remaining_seconds', models.PositiveIntegerField(blank=True, help_text='Saved server-side for connection recovery', null=True)),
                ('obj_score', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated OBJ score', max_digits=5, null=True)),
                ('tab_switch_count', models.PositiveIntegerField(default=0)),
                ('fullscreen_exit_count', models.PositiveIntegerField(default=0)),
                ('auto_submitted_reason', models.CharField(blank=True, max_length=100)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='examinations.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_submissions', to='students.student')),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Question text. Use LaTeX for math: $x^2 + y^2$')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exam_questions/')),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('text_yoruba', models.TextField(blank=True, help_text='Yoruba translation of question (optional)')),
                ('option_a_yoruba', models.TextField(blank=True, help_text='Yoruba translation of option A')),
                ('option_b_yoruba', models.TextField(blank=True, help_text='Yoruba translation of option B')),
                ('option_c_yoruba', models.TextField(blank=True, help_text='Yoruba translation of option C')),
                ('option_d_yoruba', models.TextField(blank=True, help_text='Yoruba translation of option D')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('marks', models.PositiveIntegerField(default=1, help_text='Marks for this question')),
                ('order', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='examinations.exam')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TheoryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Theory question text')),
                ('max_marks', models.PositiveIntegerField(default=10, help_text='Maximum marks for this question')),
                ('marking_guide', models.TextField(blank=True, help_text='Expected answer / key points for marking')),
                ('order', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_questions', to='examinations.exam')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca1_marks_percentage', models.PositiveIntegerField(default=20, help_text='CA1 percentage of total marks')),
                ('ca2_marks_percentage', models.PositiveIntegerField(default=20, help_text='CA2 percentage of total marks')),
                ('obj_marks_percentage', models.PositiveIntegerField(default=30, help_text='OBJ percentage of total marks')),
                ('theory_marks_percentage', models.PositiveIntegerField(default=30, help_text='Theory percentage of total marks')),
                ('total_marks', models.PositiveIntegerField(default=100, help_text='Total marks for exam (used to calculate actual marks from percentages)')),
                ('question_submission_deadline', models.DateTimeField(help_text='Deadline for teachers to submit exam questions')),
                ('exam_vetting_deadline', models.DateTimeField(help_text='Deadline for examiner to vet exam questions')),
                ('exam_approval_deadline', models.DateTimeField(help_text='Deadline for admin to approve exam')),
                ('default_exam_duration_minutes', models.PositiveIntegerField(default=60, help_text='Default duration for exam in minutes')),
                ('randomize_questions_by_default', models.BooleanField(default=True, help_text='Randomize question order for students by default')),
                ('show_results_immediately', models.BooleanField(default=False, help_text='Show exam results immediately after submission')),
                ('configured_at', models.DateTimeField(auto_now=True)),
                ('configured_by', models.ForeignKey(limit_choices_to={'roles__name__in': ['PRINCIPAL', 'VICE_PRINCIPAL']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_configs_set', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_config', to='academics.academicsession')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_configs', to='academics.term')),
            ],
            options={
                'verbose_name_plural': 'Exam Configurations',
                'unique_together': {('session', 'term')},
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca1_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ca2_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('obj_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('theory_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('remark', models.CharField(blank=True, max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examinations.exam')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_modified', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_published', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student')),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result', to='examinations.examsubmission')),
            ],
            options={
                'ordering': ['-total_score'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False, help_text='Student flagged for review')),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='examinations.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='examinations.examsubmission')),
            ],
            options={
                'unique_together': {('submission', 'question')},
            },
        ),
        migrations.CreateModel(
            name='TheoryScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('feedback', models.TextField(blank=True)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theory_scores_entered', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_scores', to='examinations.examsubmission')),
                ('theory_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='examinations.theoryquestion')),
            ],
            options={
                'unique_together': {('submission', 'theory_question')},
            },
        ),
    ]
