# Generated by Django 6.0.3 on 2026-04-03 13:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('examinations', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        # First, add all new fields
        migrations.AddField(
            model_name='exam',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Admin must set to True for students to see and access this exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Subject teacher assigned to create questions for this exam', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_teaching', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='exam',
            name='theory_attachment',
            field=models.FileField(blank=True, help_text='Upload theory/written questions file for printing (PDF, DOCX, DOC only)', null=True, upload_to='exams/theory_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'])]),
        ),
        # Alter field definitions
        migrations.AlterField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Duration for the CBT (objective) section in minutes'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(help_text='e.g., First Term Examination', max_length=255),
        ),
        # Now update unique_together (after teacher field is added)
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('subject', 'class_arm', 'teacher', 'session', 'term')},
        ),
        # Create new model
        migrations.CreateModel(
            name='ObjectiveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Type the question here (supports Yoruba Unicode characters: ṣ, ọ, ẹ, etc.)')),
                ('question_image', models.ImageField(blank=True, help_text='Diagram, graph, or math equation visual', null=True, upload_to='exams/question_images/')),
                ('option_a', models.CharField(max_length=500, verbose_name='Option A')),
                ('option_b', models.CharField(max_length=500, verbose_name='Option B')),
                ('option_c', models.CharField(max_length=500, verbose_name='Option C')),
                ('option_d', models.CharField(max_length=500, verbose_name='Option D')),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], help_text='Select the correct answer for auto-grading when students take the exam', max_length=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='examinations.exam')),
            ],
            options={
                'verbose_name': 'Objective Question',
                'verbose_name_plural': 'Objective Questions',
                'ordering': ['id'],
            },
        ),
        # Update StudentAnswer relation
        migrations.AlterField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='examinations.objectivequestion'),
        ),
        # Remove old fields
        migrations.RemoveField(
            model_name='exam',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='ca1_marks',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='ca2_marks',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='deadline_penalty_logged',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='obj_marks',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='randomize_questions',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='show_result_immediately',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='status',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='submission_deadline',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='theory_marks',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='vetted_at',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='vetted_by',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='vetting_comment',
        ),
        # Delete old model
        migrations.DeleteModel(
            name='Question',
        ),
    ]
