# Generated by Django 6.0.3 on 2026-04-03 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0002_alter_exam_unique_together_exam_is_published_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='approval_comments',
            field=models.TextField(blank=True, help_text='Comments from examiner/VP/Principal', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Question approval status by examiner/VP/Principal', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
