# Generated by Django 6.0.3 on 2026-04-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0004_exam_status_and_rejection_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='approval_comments',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='is_published',
        ),
    ]
