# Generated by Django 6.0.3 on 2026-04-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_subjectteacherassignment_unique_together'),
        ('examinations', '0005_remove_exam_approval_comments_and_more'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set(),  # Remove old unique constraint
        ),
        migrations.AddField(
            model_name='exam',
            name='class_arms',
            field=models.ManyToManyField(help_text='Select all classes that will take this exam', related_name='exams', to='academics.classarm'),
        ),
        migrations.RemoveField(
            model_name='exam',
            name='class_arm',
        ),
    ]
