# Generated by Django 6.0.3 on 2026-04-06 21:46

from django.db import migrations
from django.db.models import Count


def consolidate_and_remove_duplicates(apps, schema_editor):
    """Remove duplicate exams while consolidating their class_arms"""
    Exam = apps.get_model('examinations', 'Exam')
    
    # Find duplicate exams
    duplicates = Exam.objects.values('subject', 'teacher', 'session', 'term').annotate(
        count=Count('id')
    ).filter(count__gt=1)
    
    for dup_group in duplicates:
        # Get all exams in this duplicate group, ordered by ID (keep the latest)
        exams_in_group = list(Exam.objects.filter(
            subject=dup_group['subject'],
            teacher=dup_group['teacher'],
            session=dup_group['session'],
            term=dup_group['term']
        ).order_by('id'))
        
        if len(exams_in_group) > 1:
            keeper = exams_in_group[-1]  # Keep the last one (highest ID)
            duplicates_to_delete = exams_in_group[:-1]  # Delete the others
            
            # Consolidate class_arms from duplicates to keeper
            for duplicate in duplicates_to_delete:
                for class_arm in duplicate.class_arms.all():
                    keeper.class_arms.add(class_arm)
                duplicate.delete()


def reverse_consolidate(apps, schema_editor):
    """Reverse is not applicable for this migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0006_alter_exam_unique_together_exam_class_arms_and_more'),
    ]

    operations = [
        migrations.RunPython(consolidate_and_remove_duplicates, reverse_consolidate),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('subject', 'teacher', 'session', 'term')},
        ),
    ]
