# Generated by Django 6.0.3 on 2026-04-07 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0007_remove_duplicate_exams'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubmission',
            name='last_activity_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time student interacted with exam'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='last_autosave_at',
            field=models.DateTimeField(blank=True, help_text='Last time answers were auto-saved', null=True),
        ),
        migrations.CreateModel(
            name='MalpracticeViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('TAB_SWITCH', 'Tab Switch'), ('FULLSCREEN_EXIT', 'Fullscreen Exit'), ('IDLE_TIMEOUT', 'Idle Timeout')], max_length=20)),
                ('violation_count', models.PositiveIntegerField(default=1, help_text='Number of times this violation occurred')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='examinations.examsubmission')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['submission', 'timestamp'], name='examination_submiss_320ca2_idx')],
            },
        ),
    ]
