# Generated by Django 6.0.3 on 2026-04-07 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0008_examsubmission_last_activity_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='scheduled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_scheduled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='scheduled_end_datetime',
            field=models.DateTimeField(blank=True, help_text='Date and time when students can no longer submit exam', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='scheduled_start_datetime',
            field=models.DateTimeField(blank=True, help_text='Date and time when students can start taking this exam', null=True),
        ),
    ]
