# Generated by Django 6.0.3 on 2026-04-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0009_exam_scheduled_at_exam_scheduled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='randomize_questions',
            field=models.BooleanField(default=True, help_text='Shuffle question order for each student taking the exam'),
        ),
    ]
