# Generated by Django 6.0.3 on 2026-04-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0010_exam_randomize_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='examconfiguration',
            name='exam_start_date',
            field=models.DateTimeField(blank=True, help_text='Official start date for exams. Upcoming exams become visible on student dashboard from this date.', null=True),
        ),
    ]
