# Generated by Django 6.0.3 on 2026-04-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0011_examconfiguration_exam_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='examconfiguration',
            name='exam_end_date',
            field=models.DateTimeField(blank=True, help_text='Official end date for exams. After this date, exams are hidden from the student dashboard.', null=True),
        ),
    ]
