# Generated by Django 6.0.3 on 2026-04-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0012_examconfiguration_exam_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examconfiguration',
            name='exam_approval_deadline',
        ),
        migrations.RemoveField(
            model_name='examconfiguration',
            name='exam_vetting_deadline',
        ),
        migrations.RemoveField(
            model_name='examconfiguration',
            name='randomize_questions_by_default',
        ),
        migrations.RemoveField(
            model_name='examconfiguration',
            name='show_results_immediately',
        ),
    ]
