# Generated by Django 6.0.3 on 2026-04-17 09:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0014_exam_show_results_immediately'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubmission',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address used for the last activity', null=True),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='pin_verified',
            field=models.BooleanField(default=False, help_text="True if the student has successfully entered today's PIN for this subject"),
        ),
        migrations.CreateModel(
            name='DailyExamPIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('pin', models.CharField(max_length=10)),
                ('valid_until', models.DateTimeField(help_text='After this time, the PIN is no longer valid for starting new exams')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_pins_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Exam PIN',
                'verbose_name_plural': 'Daily Exam PINs',
                'ordering': ['-date'],
            },
        ),
    ]
