# Generated by Django 6.0.3 on 2026-04-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0015_examsubmission_client_ip_examsubmission_pin_verified_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='malpracticeviolation',
            name='examination_submiss_320ca2_idx',
        ),
        migrations.DeleteModel(
            name='MalpracticeViolation',
        ),
    ]
