# Generated by Django 6.0.3 on 2026-04-25 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0016_remove_malpractice_violation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='theory_attachment',
            field=models.FileField(blank=True, help_text='Upload theory/written questions file (PDF or TXT only)', null=True, upload_to='exams/theory_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt'])]),
        ),
    ]
